export const translations = {
  en: {
    // App.tsx
    headerTitle: 'Anshim Scanner',
    toggleToKorean: '한국어로 보기',
    toggleToEnglish: 'View in English',
    analysisFailedTitle: 'Analysis Failed',
    tryAgainButton: 'Try Again',
    footerText: '© {year} Anshim Scanner. All rights reserved.',
    userManualLink: 'User Manual',
    legalDisclaimerLink: 'Legal Disclaimer',
    
    // DisclaimerModal.tsx
    disclaimerTitle: 'Legal Disclaimer',
    disclaimerContent1: 'For Informational Purposes Only: All analysis results provided by \'Anshim Scanner\' are generated by Google Gemini AI and are intended for informational purposes only.',
    disclaimerContent2: 'Not a Substitute for Professional Advice: The information in this app is not a substitute for medical, legal, or other professional advice. If you have health concerns related to product use, please consult a doctor or a qualified professional.',
    disclaimerContent3: 'Limitation of Liability: AI-generated analysis may contain errors or inaccuracies. Users are solely responsible for all decisions made based on the information provided. The development team is not liable for any direct or indirect damages arising from the use of this application.',
    iUnderstandButton: 'I Understand',

    // UserManualModal.tsx
    userManualTitle: 'User Manual',
    closeButton: 'Close',
    userManualSections: [
      {
        title: '1. Getting Started',
        content: "When you first launch the app, you'll see the initial screen for scanning product labels. You can choose an analysis mode ('Household Product' or 'Food') and select your preferred language (Korean/English)."
      },
      {
        title: '2. Scanning and Analyzing a Product Label',
        content: "1. Select Mode: Choose 'Household Product' or 'Food' at the top.\n2. Prepare Images: Get clear, well-lit photos of the product's ingredient list.\n3. Upload Images: Use 'Upload Image(s)' to select stored photos or 'Take Photo' to use your camera.\n4. Review Previews: Check uploaded images and remove incorrect ones using the 'X' button.\n5. Start Analysis: Click the 'Analyze X Image(s)' button to begin."
      },
      {
        title: '3. Understanding the Results',
        content: "- Key Findings: Get an at-a-glance overview with scores and a summary.\n- For Household Products: Use 'Vulnerable Group Analysis' for a personalized analysis.\n- For Food: Check for 'Allergen Info', 'Food Additive Analysis', and a 'Nutritional Summary'.\n- Detailed Information: Explore cards for 'Safety Tips', 'Ingredient Deep Dive', and more."
      },
      {
        title: '4. Using the Results and Starting Over',
        content: "- Save and Share: Use the icons at the bottom to 'Copy Text', 'Save as JPG', or 'Save as TXT'.\n- Start Over: Click the 'Scan Another Product' button to return to the initial screen."
      }
    ],

    // Scanner.tsx
    analysisModeHousehold: "Household Product",
    analysisModeFood: "Food",
    scanTitle: 'Scan a Product Label',
    scanFoodTitle: 'Scan a Food Label',
    multiOcrInfo: 'For best results, upload clear, well-lit photos of the ingredient list for products like cleaners, shampoos, or detergents. If the list is long, feel free to upload multiple images.',
    foodScanInfo: 'For best results, upload clear, well-lit photos of the ingredient list to check for food additives like aspartame or sodium nitrate. If the list is long, feel free to upload multiple images.',
    imagePreviewAlt: 'Image preview {index}',
    ocrButton: 'Upload Image(s)',
    addPhotoButton: 'Take Photo',
    analyzeButton: 'Analyze {count} Image(s)',

    // Spinner.tsx
    loadingText: 'Preparing analysis...',
    loadingText_contacting: 'Contacting Gemini...',
    loadingText_analyzing: 'Analyzing product data...',
    loadingText_generating: 'Generating your report...',

    // ResultDisplay.tsx (and its subcomponents)
    scanAgainButton: 'Scan Another Product',
    scannedImagesTitle: 'Scanned Images',
    analysisSummary: 'Key Findings',
    grade: 'Safety Grade',
    score: 'Score',
    safetyTips: 'Safety & Mitigation Tips',
    notes: 'Analyst Notes',
    ingredientDeepDive: 'Ingredient Deep Dive',
    riskLevel: 'Risk Level',
    hazards: 'Hazards',
    concentration: 'Concentration',
    incidentHistory: 'Incident History',
    noIncidents: 'No relevant incidents found.',
    incidentType: 'Type',
    date: 'Date',
    saferAlternatives: 'Safer Alternatives',
    noAlternatives: 'No specific alternatives recommended.',
    reason: 'Reason',
    environmentalImpact: 'Environmental Impact',
    ecoGrade: 'Eco-Grade',
    ecoScore: 'Eco-Score',
    packaging: 'Packaging Recyclability',
    keyFactors: 'Key Factors',
    disposalTip: 'Safe Disposal Tip',
    vulnerableGroupAnalysis: 'Vulnerable Group Analysis',
    vulnerableGroupPrompt: 'Refine analysis for specific sensitivities:',
    refining: 'Refining...',
    refinedAnalysisTitle: 'Detailed Analysis for {group}',
    baseAnalysisTitle: 'Base Analysis',
    productName: 'Product Name',
    category: 'Category',
    byBrand: 'by {brand}',
    noDataAvailable: 'No data available.',
    reportDate: 'Report Date',
    gradeSubtitles: {
        'Safe': 'Low risk detected for general use.',
        'Caution': 'Some ingredients may pose moderate risks. Use with care.',
        'High Risk': 'Contains ingredients with significant health & safety concerns.',
        'Eco-Friendly': 'Low environmental impact.',
        'Moderate Impact': 'Some environmental concerns identified.',
        'High Impact': 'Significant environmental impact.',
        'Good': 'Considered to have a positive nutritional profile.',
        'Moderate': 'Has both positive and negative nutritional aspects.',
        'Poor': 'Considered to have a negative nutritional profile.'
    },
    // New Food-specific strings
    foodSafetyGrade: 'Food Safety Grade',
    nutritionalGrade: 'Nutritional Grade',
    allergenInfo: 'Allergen Information',
    allergenContains: 'Contains',
    allergenMayContain: 'May Contain',
    foodAdditiveAnalysis: 'Food Additive Analysis',
    purpose: 'Purpose',
    permissibleIntakeADI: 'ADI Note',
    adiDescription: '(Acceptable Daily Intake: The maximum amount of a substance that can be consumed daily over a lifetime without posing a significant health risk.)',
    nutritionalSummary: 'Nutritional Summary',

    // Actions
    copyReport: 'Copy Text',
    reportCopied: 'Copied!',
    shareReport: 'Share',
    saveAsJpg: 'Save as JPG',
    saveAsTxt: 'Save as TXT',
    saving: 'Saving...',
    saved: 'Saved!',
    reportTitle: 'Anshim Scanner Analysis Report',


    // vulnerable modes from services/geminiService.ts
    vulnerableModes: {
        Infant: 'Infants',
        Pregnant: 'Pregnant Individuals',
        Pet: 'Pets',
        Respiratory: 'Individuals with Respiratory Sensitivities',
    },
  },
  ko: {
    // App.tsx
    headerTitle: '안심 스캐너',
    toggleToKorean: '한국어로 보기',
    toggleToEnglish: 'View in English',
    analysisFailedTitle: '분석 실패',
    tryAgainButton: '다시 시도',
    footerText: '© {year} 안심 스캐너. All rights reserved.',
    userManualLink: '사용자 매뉴얼',
    legalDisclaimerLink: '법적 고지',

    // DisclaimerModal.tsx
    disclaimerTitle: '법적 고지',
    disclaimerContent1: '정보 제공 목적: \'안심 스캐너\'가 제공하는 모든 분석 결과는 Google Gemini AI를 통해 생성된 정보이며, 참고용으로만 제공됩니다.',
    disclaimerContent2: '전문가 조언 대체 불가: 본 앱의 정보는 의학적, 법률적 또는 기타 전문적인 조언을 대체할 수 없습니다. 제품 사용과 관련된 건강상의 우려가 있는 경우, 반드시 의사나 전문가와 상담하시기 바랍니다.',
    disclaimerContent3: '책임의 한계: AI 분석에는 오류나 부정확성이 포함될 수 있습니다. 사용자는 제공된 정보를 바탕으로 내린 모든 결정에 대해 스스로 책임을 져야 하며, 개발팀은 이로 인해 발생하는 어떠한 직간접적인 손해에 대해서도 책임을 지지 않습니다.',
    iUnderstandButton: '확인 및 동의',

    // UserManualModal.tsx
    userManualTitle: '사용자 매뉴얼',
    closeButton: '닫기',
    userManualSections: [
      {
        title: '1. 시작하기',
        content: "앱을 처음 실행하면 분석 모드('생활화학제품' 또는 '식품')를 선택하고, 우측 상단에서 언어(한국어/영어)를 선택할 수 있습니다."
      },
      {
        title: '2. 제품 라벨 스캔 및 분석',
        content: "1. 모드 선택: 상단에서 '생활화학제품' 또는 '식품'을 선택합니다.\n2. 이미지 준비: 분석할 제품의 성분 목록이 잘 보이도록 선명한 사진을 준비합니다.\n3. 이미지 업로드: '이미지 업로드'로 사진을 선택하거나, '사진 찍기'로 직접 촬영합니다.\n4. 미리보기 확인: 업로드한 이미지를 확인하고, 잘못된 이미지는 'X' 버튼으로 삭제합니다.\n5. 분석 시작: 하단의 'N개 이미지 분석' 버튼을 클릭하여 분석을 시작합니다."
      },
      {
        title: '3. 분석 결과 확인하기',
        content: "- 주요 분석 결과: 점수와 요약으로 핵심 정보를 한눈에 파악합니다.\n- 생활화학제품: '취약 계층 분석' 기능으로 맞춤형 분석을 확인합니다.\n- 식품: '알레르기 정보', '식품첨가물 분석', '영양 분석'을 확인합니다.\n- 상세 정보: '안전 사용 가이드', '성분 심층 분석' 등 카드별 상세 내용을 확인합니다."
      },
      {
        title: '4. 결과 활용 및 새로 시작하기',
        content: "- 결과 저장/공유: 하단 메뉴에서 '텍스트 복사', 'JPG로 저장', 'TXT로 저장'이 가능합니다.\n- 새로 시작하기: '다른 제품 스캔하기' 버튼을 눌러 초기 화면으로 돌아갑니다."
      }
    ],

    // Scanner.tsx
    analysisModeHousehold: "생활화학제품",
    analysisModeFood: "식품",
    scanTitle: '생활화학제품 라벨 스캔하기',
    scanFoodTitle: '식품 라벨 스캔하기',
    multiOcrInfo: '정확한 분석을 위해, 생활화학제품(예: 세정제, 샴푸, 방향제 등)의 전성분표를 선명하게 촬영하여 업로드해주세요. 성분 목록이 길 경우 여러 장을 추가할 수 있습니다.',
    foodScanInfo: '정확한 분석을 위해, 식품첨가물(예: 아스파탐, 아질산나트륨 등) 확인을 위한 원재료명 부분을 선명하게 촬영하여 업로드해주세요. 목록이 길 경우 여러 장을 추가할 수 있습니다.',
    imagePreviewAlt: '이미지 미리보기 {index}',
    ocrButton: '이미지 업로드',
    addPhotoButton: '사진 찍기',
    analyzeButton: '{count}개 이미지 분석',

    // Spinner.tsx
    loadingText: '분석 준비 중...',
    loadingText_contacting: 'Gemini에 연결 중...',
    loadingText_analyzing: '제품 데이터 분석 중...',
    loadingText_generating: '보고서 생성 중...',

    // ResultDisplay.tsx (and its subcomponents)
    scanAgainButton: '다른 제품 스캔하기',
    scannedImagesTitle: '스캔된 이미지',
    analysisSummary: '주요 분석 결과',
    grade: '안전 등급',
    score: '점수',
    safetyTips: '안전 사용 가이드',
    notes: '분석가 노트',
    ingredientDeepDive: '성분 심층 분석',
    riskLevel: '위험도',
    hazards: '유해성',
    concentration: '농도',
    incidentHistory: '과거 사고 이력',
    noIncidents: '관련된 사고 이력을 찾을 수 없습니다.',
    incidentType: '유형',
    date: '날짜',
    saferAlternatives: '더 안전한 대안 제품',
    noAlternatives: '추천된 특정 대안 제품이 없습니다.',
    reason: '이유',
    environmentalImpact: '환경 영향',
    ecoGrade: '환경 등급',
    ecoScore: '환경 점수',
    packaging: '포장재 재활용성',
    keyFactors: '주요 요인',
    disposalTip: '안전한 폐기 팁',
    vulnerableGroupAnalysis: '취약 계층을 위한 분석 세분화',
    vulnerableGroupPrompt: '특정 민감도에 대한 분석 세분화:',
    refining: '분석 중...',
    refinedAnalysisTitle: '{group}에 대한 상세 분석',
    baseAnalysisTitle: '일반 분석',
    productName: '제품명',
    category: '제품 유형',
    byBrand: '브랜드: {brand}',
    noDataAvailable: '데이터 없음.',
    reportDate: '분석 일자',
    gradeSubtitles: {
        'Safe': '일반 사용에 대해 낮은 위험이 감지되었습니다.',
        'Caution': '일부 성분에 중간 수준의 위험이 있을 수 있습니다. 주의하여 사용하세요.',
        'High Risk': '건강 및 안전에 대한 심각한 우려가 있는 성분을 포함합니다.',
        'Eco-Friendly': '환경 영향이 적습니다.',
        'Moderate Impact': '일부 환경적 우려가 확인되었습니다.',
        'High Impact': '환경에 미치는 영향이 상당합니다.',
        'Good': '긍정적인 영양 프로필을 가지고 있습니다.',
        'Moderate': '긍정적 및 부정적 영양 측면을 모두 가집니다.',
        'Poor': '부정적인 영양 프로필을 가지고 있습니다.'
    },
    
    // New Food-specific strings
    foodSafetyGrade: '식품 안전 등급',
    nutritionalGrade: '영양 등급',
    allergenInfo: '알레르기 정보',
    allergenContains: '포함',
    allergenMayContain: '혼입 가능',
    foodAdditiveAnalysis: '식품첨가물 분석',
    purpose: '목적',
    permissibleIntakeADI: 'ADI 정보',
    adiDescription: '(일일섭취허용량: 평생 동안 매일 섭취해도 건강에 해를 끼치지 않는 것으로 인정되는 최대량)',
    nutritionalSummary: '영양 분석',

    // Actions
    copyReport: '텍스트 복사',
    reportCopied: '복사됨!',
    shareReport: '공유하기',
    saveAsJpg: 'JPG로 저장',
    saveAsTxt: 'TXT로 저장',
    saving: '저장 중...',
    saved: '저장됨!',
    reportTitle: '안심 스캐너 분석 보고서',

    // vulnerable modes from services/geminiService.ts
    vulnerableModes: {
        Infant: '영유아',
        Pregnant: '임산부',
        Pet: '반려동물',
        Respiratory: '호흡기 민감군',
    },
  }
};