export const translations = {
  en: {
    // App.tsx
    headerTitle: 'Anshim Scanner',
    toggleToKorean: '한국어로 보기',
    toggleToEnglish: 'View in English',
    analysisFailedTitle: 'Analysis Failed',
    tryAgainButton: 'Try Again',
    footerText: '© 2025 Anshim Scanner. An entry for the AI Idea Contest to Solve Social Problems in Environment/Safety/Health hosted by the Forest and Sharing Foundation and The Hankyoreh.',
    userManualLink: 'User Manual',
    legalDisclaimerLink: 'Legal Disclaimer',
    
    // DisclaimerModal.tsx
    disclaimerTitle: 'Important Disclaimer',
    disclaimerContent1: 'Project Purpose: This app was developed for a competition under the theme of "Solving Social Issues in Environment/Safety/Health using AI." It is a proof-of-concept demonstrating AI capabilities and is not a commercial product.',
    disclaimerContent2: 'For Informational Purposes Only: All analysis results are generated by AI and are for informational purposes only. They may contain inaccuracies or omissions.',
    disclaimerContent3: 'Not a Substitute for Professional Advice: This app DOES NOT PROVIDE MEDICAL ADVICE. The information, especially regarding medicines, is not a substitute for professional medical advice, diagnosis, or treatment. Always consult a doctor or pharmacist for any health concerns.',
    disclaimerContent4: 'Limitation of Liability: The development team is not liable for any damages arising from the use of this app. Users are solely responsible for all decisions and actions based on the information provided.',
    iUnderstandButton: 'I Understand and Agree',

    // UserManualModal.tsx
    userManualTitle: 'User Manual',
    closeButton: 'Close',
    userManualSections: [
      {
        title: '1. What is Anshim Scanner? (Features & Purpose)',
        content: "Anshim Scanner is an app that uses AI to analyze complex product ingredient lists, providing users with an easy-to-understand 'Risk Report'.\n\nIt was created to resolve information asymmetry between consumers and companies, and to address environmental pollution from improper product disposal. This app is an entry for the 'AI Idea Contest to Solve Social Problems in Environment/Safety/Health', hosted by the Forest and Sharing Foundation and The Hankyoreh newspaper.\n\n[Key Features]\n- Automatic Classification: Intelligently identifies products as Household, Food, or Medicine.\n- Comprehensive Analysis: Assesses risks to both human health and the environment.\n- Refined Analysis: Re-evaluates risks for vulnerable groups like infants or pregnant individuals.\n- Safe Disposal Guide: Provides instructions for proper disposal to prevent pollution."
      },
      {
        title: '2. How to Use (Product Analysis Steps)',
        content: "1. Prepare Ingredient Info\n- Take a clear photo of the entire ingredient list or copy the text.\n- Tip: Better lighting and clearer text improve AI recognition. You can upload multiple images for long ingredient lists.\n\n2. Input Information\n- Attach photos using 'Upload Image(s)' or 'Take Photo'.\n- Alternatively, paste the text into the 'Enter Ingredients Manually' field.\n\n3. Start Analysis\n- Click the 'Analyze' button.\n- The AI will automatically determine the product type and begin an in-depth analysis, which typically takes 15-30 seconds."
      },
      {
        title: '3. Reading the Analysis Report',
        content: `The report is broadly divided into 'Key Findings' and 'Detailed Analysis'.

[Key Findings]
This section provides an at-a-glance overview of the product's core risks, featuring the 'Risk Score' gauge and the AI's overall summary.

[Detailed Analysis by Product Type]
- Household Products: Delves into ingredients that may be harmful to humans, the potential for environmental pollution, and safe disposal methods.
- Food: Informs you about potential allergens, the purpose and safety of approved food additives that may require caution, and an overall nutritional grade.
- Medicine: Clearly explains the active ingredients that produce the drug's effect, potential side effects (both common and rare), and 'contraindications'—situations where the drug should not be used. (Always remember this is not medical advice.)

[Term Definitions]
For difficult technical terms like 'Endocrine Disruptor' or 'ADI' in the report, you can find simple explanations within the app's tooltips, making complex information accessible.`
      },
      {
        title: '4. Utilizing the Report & Special Features',
        content: "[Vulnerable Group Analysis (Household Products Only)]\nSelect a group like 'Infants' or 'Pregnant Individuals' to re-analyze the risk, focusing on ingredients that could affect them more acutely. This helps you choose safer products for your family.\n\n[Save & Share Results]\nUse the icons at the bottom of the report to copy the analysis as text or save the entire report as an image (JPG) file to keep a record and share."
      },
      {
        title: '5. Expected Effects & Social Value',
        content: "- Consumer Empowerment: Enables consumers to easily understand product information and make safer choices.\n- Promoting Corporate Responsibility: Encourages companies to develop safer, eco-friendly products in response to informed consumer demand.\n- Environmental Protection: Helps prevent soil and water pollution by providing proper disposal guidance."
      },
      {
        title: '6. Troubleshooting (FAQ)',
        content: `Q. The analysis fails or takes too long.
A. Please check your internet connection. If the problem persists, try taking a clearer picture or try again after a short while. The AI server may be experiencing temporary high traffic.

Q. Text is not detected from the image.
A. Recognition can fail if the photo is blurry, the lighting is poor, or there are shadows on the text. Try taking a clear photo in a well-lit area, ensuring the entire ingredient list is visible. You can also upload multiple images to cover the full list.

Q. The product type (Household/Food/Drug) was classified incorrectly.
A. The AI classifies based on the ingredient list, but errors can occasionally occur. In this case, manually entering the ingredient text can lead to a more accurate analysis.`
      },
      {
        title: '7. Privacy and Data',
        content: `Anshim Scanner values your privacy. Uploaded images and text are used solely as input for the AI model to perform the analysis and are not stored on our servers. All data is deleted immediately after the analysis is complete, so you can use the app with peace of mind.`
      }
    ],

    // Scanner.tsx
    scanTitle: 'Scan or Enter Product Ingredients',
    scanInfo: "Simply scan any product, and our AI will automatically identify its type—whether it's a household cleaner, a food item, or medicine. This smart classification ensures you receive the most accurate and relevant safety analysis, tailored specifically to your product.",
    imagePreviewAlt: 'Image preview {index}',
    ocrButton: 'Upload Image(s)',
    addPhotoButton: 'Take Photo',
    orDivider: 'OR',
    textInputLabel: 'Enter Ingredients Manually',
    textInputPlaceholder: 'e.g., Water, Sodium Laureth Sulfate... OR Wheat Flour, Palm Oil... OR Acetaminophen, Ibuprofen...',
    analyzeButton: 'Analyze {count} Image(s)',
    analyzeTextButton: 'Analyze Ingredients',

    // Spinner.tsx
    loadingText: 'Preparing analysis...',
    loadingText_contacting: 'Contacting Gemini...',
    loadingText_classifying: 'Classifying product type...',
    loadingText_analyzing: 'Analyzing product data...',
    loadingText_generating: 'Generating your report...',

    // ResultDisplay.tsx (and its subcomponents)
    scanAgainButton: 'Scan Another Product',
    scannedImagesTitle: 'Scanned Images',
    analysisSummary: 'Key Findings',
    riskGrade: 'Risk Grade',
    riskScore: 'Risk Score',
    safetyTips: 'Safety & Mitigation Tips',
    notes: 'Analyst Notes',
    ingredientDeepDive: 'Ingredient Deep Dive',
    riskLevel: 'Risk Level',
    hazards: 'Hazards',
    concentration: 'Concentration',
    incidentHistory: 'Incident History',
    noIncidents: 'No relevant incidents found.',
    incidentType: 'Type',
    date: 'Date',
    saferAlternatives: 'Safer Alternatives',
    noAlternatives: 'No specific alternatives recommended.',
    reason: 'Reason',
    environmentalImpact: 'Environmental Impact',
    ecoRiskGrade: 'Environmental Risk',
    ecoRiskScore: 'Eco-Risk Score',
    packaging: 'Packaging Recyclability',
    keyFactors: 'Key Factors',
    disposalTip: 'Safe Disposal Tip',
    vulnerableGroupAnalysis: 'Vulnerable Group Analysis',
    vulnerableGroupPrompt: 'Refine analysis for specific sensitivities:',
    refining: 'Refining...',
    refinedAnalysisTitle: 'Detailed Analysis for {group}',
    productName: 'Product Name',
    category: 'Category',
    byBrand: 'by {brand}',
    noDataAvailable: 'No data available.',
    reportDate: 'Report Date',
    riskGradeSubtitles: {
        'Low Risk': 'Low risk detected for general use under normal conditions.',
        'Caution': 'Some ingredients may pose moderate risks. Use with care.',
        'High Risk': 'Contains ingredients with significant health, safety, or environmental concerns.',
        'Eco-Friendly': 'Low environmental risk.',
        'Moderate Impact': 'Some environmental concerns identified.',
        'High Impact': 'Significant environmental risk.'
    },
    nutritionalGradeSubtitles: {
        'Good': 'Considered to have a positive nutritional profile.',
        'Moderate': 'Has both positive and negative nutritional aspects.',
        'Poor': 'Considered to have a negative nutritional profile.'
    },
    // Food-specific strings
    foodSafetyGrade: 'Food Safety Grade',
    nutritionalGrade: 'Nutritional Grade',
    allergenInfo: 'Allergen Information',
    allergenContains: 'Contains',
    allergenMayContain: 'May Contain',
    foodAdditiveAnalysis: 'Food Additive Analysis',
    purpose: 'Purpose',
    permissibleIntakeADI: 'ADI Note',
    adiDescription: '(Acceptable Daily Intake: The maximum amount of a substance that can be consumed daily over a lifetime without posing a significant health risk.)',
    nutritionalSummary: 'Nutritional Summary',
    
    // Drug-specific strings
    analysisModeDrug: "Medicines",
    drugWarning: "This is not medical advice. Consult a doctor or pharmacist.",
    activeIngredients: "Active Ingredients",
    function: "Function",
    sideEffects: "Potential Side Effects",
    frequency: "Frequency",
    contraindications: "Contraindications (Do Not Use If...)",
    condition: "Condition / Substance",

    // Actions
    copyReport: 'Copy Text',
    reportCopied: 'Copied!',
    saveAsJpg: 'Save as JPG',
    saveAsTxt: 'Save as TXT',
    saving: 'Saving...',
    saved: 'Saved!',
    reportTitle: 'Anshim Scanner Analysis Report',

    vulnerableModes: {
        Infant: 'Infants',
        Pregnant: 'Pregnant Individuals',
        Pet: 'Pets',
        Respiratory: 'Respiratory Sensitivities',
    },

    scoreInterpretationGuide: 'Score Interpretation Guide',
    meaningPrefix: 'Meaning: ',
    judgmentPrefix: 'Judgment: ',
    scoreMeaningGeneric: 'This is a 0-100 scale representing the level of health, safety, and environmental risk. A higher score indicates a higher risk.',
    riskScoreMeaning: 'Risk Score: Indicates potential risk to human health (0-100). A higher score requires more caution.',
    ecoScoreMeaning: 'Eco-Risk Score: Indicates potential environmental impact, including improper disposal (0-100). A higher score means greater harm.',


    // Definitions for tooltips
    definitions: {
        riskScore: 'A score from 0-100 indicating the potential level of health, safety, and environmental risk. A higher score means higher risk.',
        ecoRiskScore: 'A score from 0-100 indicating the potential environmental risk from ingredients and improper disposal. A higher score means higher risk.',
        carcinogen: 'A substance capable of causing cancer in living tissue.',
        endocrineDisruptor: 'Chemicals that can interfere with hormone systems. These disruptions can cause cancerous tumors, birth defects, and other developmental disorders.',
        adi: 'Acceptable Daily Intake: The amount of a substance that can be ingested daily over a lifetime without an appreciable health risk.',
        contraindication: 'A specific situation in which a drug, procedure, or surgery should not be used because it may be harmful to the person.'
    }
  },
  ko: {
    // App.tsx
    headerTitle: '안심 스캐너',
    toggleToKorean: '한국어로 보기',
    toggleToEnglish: 'View in English',
    analysisFailedTitle: '분석 실패',
    tryAgainButton: '다시 시도',
    footerText: '© 2025 안심 스캐너. (재)숲과나눔과 한겨레 주최 AI 활용 환경/안전/보건 분야 사회문제 해결 아이디어 공모전 출품작.',
    userManualLink: '사용자 매뉴얼',
    legalDisclaimerLink: '법적 고지',

    // DisclaimerModal.tsx
    disclaimerTitle: '중요 고지사항',
    disclaimerContent1: '프로젝트 목적: 본 앱은 "AI를 활용한 환경/안전/보건 분야 사회문제 해결"을 주제로 한 공모전 출품을 위해 개발된 프로토타입이며, 상업용 서비스가 아닙니다.',
    disclaimerContent2: '정보 제공 목적: 모든 분석 결과는 AI에 의해 생성되며, 정보 제공 목적으로만 사용되어야 합니다. 내용에 부정확성이나 누락이 있을 수 있습니다.',
    disclaimerContent3: '전문가 조언 대체 불가: 본 앱은 의료 자문을 제공하지 않습니다. 특히 의약품 관련 정보는 전문적인 의학적 조언, 진단, 치료를 대체할 수 없습니다. 건강 관련 문제는 반드시 의사 또는 약사와 상담하십시오.',
    disclaimerContent4: '책임의 한계: 개발팀은 본 앱의 사용으로 인해 발생하는 어떠한 손해에 대해서도 책임을 지지 않습니다. 제공된 정보를 바탕으로 한 모든 결정과 행동의 책임은 전적으로 사용자에게 있습니다.',
    iUnderstandButton: '내용을 확인했으며 동의합니다',

    // UserManualModal.tsx
    userManualTitle: '사용자 매뉴얼',
    closeButton: '닫기',
    userManualSections: [
      {
        title: '1. 안심 스캐너란? (기능 및 개발 목적)',
        content: `안심 스캐너는 복잡한 제품 성분표를 AI로 분석하여 소비자가 이해하기 쉬운 '위험도 보고서'를 제공하는 앱입니다. 소비자와 기업 간의 정보 불균형을 해소하고, 부적절한 제품 폐기로 인한 환경오염 문제를 해결하는 데 기여하고자 '(재)숲과나눔과 한겨레가 주최하는 AI를 활용해 환경/안전/보건 분야의 사회문제 해결 아이디어 공모전' 출품작으로 제작하였습니다.
[주요 기능]
- 제품 유형 자동 분류 (생활화학제품, 식품, 의약품)
- 인체 및 환경 유해성 종합 분석
- 취약 계층 맞춤형 위험도 재분석
- 안전한 제품 폐기 방법 안내`
      },
      {
        title: '2. 활용 방법 (제품 분석 절차)',
        content: `1. 성분 정보 준비
- 분석하고 싶은 제품의 성분표 전체가 선명하게 보이도록 촬영하거나, 텍스트로 복사합니다.
- 팁: 조명이 밝고 글자가 선명할수록 AI 인식률이 높아집니다. 성분표가 길 경우 여러 장의 사진을 업로드할 수 있습니다.
2. 정보 입력
- '이미지 업로드' 또는 '사진 찍기' 버튼으로 사진을 첨부합니다.
- 또는, 복사한 성분 텍스트를 '성분 직접 입력' 란에 붙여넣습니다.
3. 분석 시작
- '분석하기' 버튼을 누릅니다.
- AI가 자동으로 제품 유형을 판별하고 약 15~30초 동안 심층 분석을 진행합니다.`
      },
      {
        title: '3. 분석 보고서 상세히 보기',
        content: `보고서는 크게 '주요 분석 결과'와 '상세 분석' 두 부분으로 나뉩니다.

[주요 분석 결과]
제품의 핵심 위험도를 한눈에 파악할 수 있도록 '위험도 점수' 게이지와 AI의 종합적인 요약평가를 보여줍니다.

[제품 유형별 상세 분석]
- 생활화학제품: 인체에 유해할 수 있는 성분, 환경오염 유발 가능성, 안전한 폐기 방법을 심층적으로 다룹니다.
- 식품: 알레르기를 유발할 수 있는 성분, 허가되었지만 주의가 필요한 식품첨가물의 역할과 안전성, 전반적인 영양 등급을 알려줍니다.
- 의약품: 약의 효과를 내는 주성분, 흔하거나 드물게 나타날 수 있는 부작용, 특정 질환이나 다른 약과 함께 사용하면 안 되는 '금기사항' 등을 명확히 설명합니다. (의료 자문이 아님을 항상 기억하세요.)

[용어 설명]
보고서에 등장하는 '내분비계 교란물질', 'ADI' 등 어려운 전문 용어는 앱 내의 툴팁을 통해 쉬운 설명을 바로 확인할 수 있어 복잡한 정보도 쉽게 이해할 수 있습니다.`
      },
      {
        title: '4. 보고서 활용 및 특수 기능',
        content: `[취약 계층 분석 (생활화학제품 전용)]
'영유아', '임산부' 등 특정 그룹을 선택하면 해당 그룹에 민감한 성분을 가중하여 위험도를 재분석합니다. 이를 통해 가족 구성원에게 더 안전한 제품을 선택할 수 있습니다.
[결과 저장 및 공유]
보고서 하단 아이콘을 통해 분석 결과를 텍스트로 복사하거나, 전체 보고서를 이미지(JPG) 파일로 저장하여 기록하고 공유할 수 있습니다.`
      },
      {
        title: '5. 기대 효과 및 사회적 가치',
        content: `- 소비자 주권 강화: 제품 정보를 쉽게 파악하여 안전한 제품을 선택할 권리를 보장합니다.
- 기업의 사회적 책임 촉진: 소비자의 현명한 선택을 통해 기업이 더 안전하고 친환경적인 제품을 개발하도록 유도합니다.
- 환경 보호 기여: 올바른 폐기 방법을 안내하여 토양 및 수질 오염 예방에 기여합니다.`
      },
      {
        title: '6. 문제 해결 (FAQ)',
        content: `Q. 분석이 실패하거나 너무 오래 걸려요.
A. 인터넷 연결 상태를 확인해 주세요. 문제가 지속되면 이미지를 더 선명하게 다시 찍거나, 잠시 후 다시 시도해 주세요. AI 서버에 일시적인 부하가 발생했을 수 있습니다.

Q. 이미지에서 텍스트를 인식하지 못해요.
A. 사진이 흔들리거나, 조명이 어둡거나, 글자에 그림자가 지면 인식률이 떨어질 수 있습니다. 밝은 곳에서 제품 전체 성분표가 잘 보이도록 선명하게 촬영해 보세요. 여러 장의 사진을 업로드하여 전체 내용을 포함할 수도 있습니다.

Q. 제품 유형(생활화학제품/식품/의약품)이 잘못 분류되었어요.
A. AI가 성분 목록을 기반으로 분류하지만, 간혹 오류가 발생할 수 있습니다. 이 경우, 성분 텍스트를 직접 입력하여 분석하면 더 정확한 결과를 얻을 수 있습니다.`
      },
      {
        title: '7. 개인정보 및 데이터 처리',
        content: `안심 스캐너는 사용자의 개인정보를 소중히 생각합니다. 업로드된 이미지와 텍스트는 오직 제품 분석을 위한 AI 모델의 입력값으로만 사용되며, 서버에 저장되지 않습니다. 모든 데이터는 분석 직후 삭제되므로 안심하고 사용하셔도 좋습니다.`
      }
    ],

    // Scanner.tsx
    scanTitle: '제품(생활화학제품, 식품, 의약품) 성분 스캔 또는 입력',
    scanInfo: '어떤 제품이든 스캔만 하세요. AI가 생활화학제품, 식품, 의약품인지 스스로 판단하여 제품 유형에 꼭 맞는 정확한 안전성 분석 결과를 제공해 드립니다. 사용자가 직접 제품 종류를 선택할 필요가 없어 더욱 편리하고 정확합니다.',
    imagePreviewAlt: '이미지 미리보기 {index}',
    ocrButton: '이미지 업로드',
    addPhotoButton: '사진 찍기',
    orDivider: '또는',
    textInputLabel: '성분 또는 제품명 직접 입력',
    textInputPlaceholder: '예) 정제수, 소듐라우레스설페이트... 또는 소맥분, 팜유... 또는 아세트아미노펜, 이부프로펜...',
    analyzeButton: '{count}개 이미지 분석',
    analyzeTextButton: '성분 분석하기',

    // Spinner.tsx
    loadingText: '분석 준비 중...',
    loadingText_contacting: 'Gemini에 연결 중...',
    loadingText_classifying: '제품 유형 분류 중...',
    loadingText_analyzing: '제품 데이터 분석 중...',
    loadingText_generating: '보고서 생성 중...',

    // ResultDisplay.tsx (and its subcomponents)
    scanAgainButton: '다른 제품 스캔하기',
    scannedImagesTitle: '스캔된 이미지',
    analysisSummary: '주요 분석 결과',
    riskGrade: '위험 등급',
    riskScore: '위험도 점수',
    safetyTips: '안전 사용 가이드',
    notes: '분석가 노트',
    ingredientDeepDive: '성분 심층 분석',
    riskLevel: '위험도',
    hazards: '유해성',
    concentration: '농도',
    incidentHistory: '과거 사고 이력',
    noIncidents: '관련된 사고 이력을 찾을 수 없습니다.',
    incidentType: '유형',
    date: '날짜',
    saferAlternatives: '더 안전한 대안',
    noAlternatives: '추천된 특정 대안이 없습니다.',
    reason: '이유',
    environmentalImpact: '환경 영향',
    ecoRiskGrade: '환경 위험 등급',
    ecoRiskScore: '환경 위험 점수',
    packaging: '포장재 재활용성',
    keyFactors: '주요 요인',
    disposalTip: '안전한 폐기 팁',
    vulnerableGroupAnalysis: '취약 계층 분석 세분화',
    vulnerableGroupPrompt: '특정 민감도에 대한 분석 세분화:',
    refining: '분석 중...',
    refinedAnalysisTitle: '{group}에 대한 상세 분석',
    productName: '제품명',
    category: '제품 유형',
    byBrand: '브랜드: {brand}',
    noDataAvailable: '데이터 없음.',
    reportDate: '분석 일자',
    riskGradeSubtitles: {
        'Low Risk': '일반적인 조건에서 사용 시 낮은 위험이 감지되었습니다.',
        'Caution': '일부 성분에 중간 수준의 위험이 있을 수 있습니다. 주의가 필요합니다.',
        'High Risk': '건강, 안전 또는 환경에 대한 심각한 우려가 있는 성분을 포함합니다.',
        'Eco-Friendly': '환경 위험이 낮습니다.',
        'Moderate Impact': '일부 환경적 우려가 확인되었습니다.',
        'High Impact': '환경에 미치는 영향이 상당합니다.'
    },
    nutritionalGradeSubtitles: {
        'Good': '긍정적인 영양 프로필을 가지고 있습니다.',
        'Moderate': '긍정적 및 부정적 영양 측면을 모두 가집니다.',
        'Poor': '부정적인 영양 프로필을 가지고 있습니다.'
    },
    
    // Food-specific strings
    foodSafetyGrade: '식품 안전 등급',
    nutritionalGrade: '영양 등급',
    allergenInfo: '알레르기 정보',
    allergenContains: '포함',
    allergenMayContain: '혼입 가능',
    foodAdditiveAnalysis: '식품첨가물 분석',
    purpose: '목적',
    permissibleIntakeADI: 'ADI 정보',
    adiDescription: '(일일섭취허용량: 평생 동안 매일 섭취해도 건강에 해를 끼치지 않는 것으로 인정되는 최대량)',
    nutritionalSummary: '영양 분석',

    // Drug-specific strings
    analysisModeDrug: "의약품",
    drugWarning: "이 정보는 의료 자문이 아닙니다. 반드시 의사 또는 약사와 상담하세요.",
    activeIngredients: "주요 활성 성분",
    function: "기능",
    sideEffects: "발생 가능한 부작용",
    frequency: "빈도",
    contraindications: "금기사항 (사용하면 안 되는 경우)",
    condition: "상황 / 성분",

    // Actions
    copyReport: '텍스트 복사',
    reportCopied: '복사됨!',
    saveAsJpg: 'JPG로 저장',
    saveAsTxt: 'TXT로 저장',
    saving: '저장 중...',
    saved: '저장됨!',
    reportTitle: '안심 스캐너 분석 보고서',

    vulnerableModes: {
        Infant: '영유아',
        Pregnant: '임산부',
        Pet: '반려동물',
        Respiratory: '호흡기 민감군',
    },

    scoreInterpretationGuide: '점수 해석 가이드',
    meaningPrefix: '의미 : ',
    judgmentPrefix: '판정결과 : ',
    scoreMeaningGeneric: '건강, 안전, 환경적 위험 수준을 나타내는 0-100점 척도입니다. 점수가 높을수록 위험도가 높습니다.',
    riskScoreMeaning: '위험도 점수: 인체 건강에 대한 잠재적 위험도를 나타냅니다 (0-100). 점수가 높을수록 더 많은 주의가 필요합니다.',
    ecoScoreMeaning: '환경 위험 점수: 부적절한 폐기를 포함한 잠재적 환경 영향을 나타냅니다 (0-100). 점수가 높을수록 환경에 더 해롭습니다.',

    // Definitions for tooltips
    definitions: {
        riskScore: '건강, 안전, 환경적 위험 수준을 나타내는 0-100점 척도입니다. 점수가 높을수록 위험도가 높습니다.',
        ecoRiskScore: '성분 및 부적절한 폐기로 인한 잠재적 환경 위험을 나타내는 0-100점 척도입니다. 점수가 높을수록 위험도가 높습니다.',
        carcinogen: '생체 조직에 암을 유발할 수 있는 물질입니다.',
        endocrineDisruptor: '호르몬 시스템을 방해할 수 있는 화학 물질입니다. 암 종양, 선천적 기형 및 기타 발달 장애를 유발할 수 있습니다.',
        adi: '일일섭취허용량: 평생 동안 매일 섭취해도 건강에 해를 끼치지 않는 것으로 인정되는 최대량입니다.',
        contraindication: '개인에게 해로울 수 있어 약물, 시술 또는 수술을 사용해서는 안 되는 특정 상황을 의미합니다.'
    }
  }
};