export const translations = {
  en: {
    // App.tsx
    headerTitle: 'Anshim Scanner',
    toggleToKorean: '한국어로 보기',
    toggleToEnglish: 'View in English',
    analysisFailedTitle: 'Analysis Failed',
    tryAgainButton: 'Try Again',
    footerText: '© {year} Anshim Scanner. All rights reserved.',
    userManualLink: 'User Manual',
    legalDisclaimerLink: 'Legal Disclaimer',
    
    // DisclaimerModal.tsx
    disclaimerTitle: 'Legal Disclaimer',
    disclaimerContent1: 'For Informational Purposes Only: All analysis results provided by \'Anshim Scanner\' are generated by Google Gemini AI and are intended for informational purposes only.',
    disclaimerContent2: 'Not a Substitute for Professional Advice: The information in this app is not a substitute for medical, legal, or other professional advice. If you have health concerns related to product use, please consult a doctor or a qualified professional.',
    disclaimerContent3: 'Limitation of Liability: AI-generated analysis may contain errors or inaccuracies. Users are solely responsible for all decisions made based on the information provided. The development team is not liable for any direct or indirect damages arising from the use of this application.',
    iUnderstandButton: 'I Understand',

    // UserManualModal.tsx
    userManualTitle: 'User Manual',
    closeButton: 'Close',
    userManualSections: [
      {
        title: '1. Getting Started',
        content: "When you first launch the app, you'll see the initial screen for scanning product labels. You can select your preferred language (Korean/English) in the top-right corner."
      },
      {
        title: '2. Scanning and Analyzing a Product Label',
        content: "1. Prepare Images: Get clear, well-lit photos of the product's ingredient list. For long lists, you can take multiple pictures.\n2. Upload Images: Use 'Upload Image(s)' to select stored photos or 'Take Photo' to use your camera.\n3. Review Previews: Check uploaded images and remove incorrect ones using the 'X' button.\n4. Start Analysis: Click the 'Analyze X Image(s)' button to begin the AI analysis."
      },
      {
        title: '3. Understanding the Results',
        content: "- Key Findings: Get an at-a-glance overview of the product's 'Safety Grade' and 'Eco-Grade' with scores and a summary.\n- Vulnerable Group Analysis: Click buttons like 'Infants' for a personalized analysis based on specific sensitivities.\n- Detailed Information: Explore cards for 'Safety Tips', 'Ingredient Deep Dive', 'Environmental Impact', and more."
      },
      {
        title: '4. Using the Results and Starting Over',
        content: "- Save and Share: Use the icons at the bottom to 'Copy Text', 'Save as JPG', or 'Save as TXT'.\n- Start Over: Click the 'Scan Another Product' button to return to the initial screen and analyze a new product."
      }
    ],

    // Scanner.tsx
    scanTitle: 'Scan a Product Label',
    scanModeOcr: 'Scan with Camera (OCR)',
    multiOcrInfo: 'For best results, upload clear, well-lit photos of the ingredient list. If the list is long, feel free to upload multiple images.',
    imagePreviewAlt: 'Image preview {index}',
    ocrButton: 'Upload Image(s)',
    addPhotoButton: 'Take Photo',
    analyzeButton: 'Analyze {count} Image(s)',

    // Spinner.tsx
    loadingText: 'Preparing analysis...',
    loadingText_contacting: 'Contacting Gemini...',
    loadingText_analyzing: 'Analyzing product data...',
    loadingText_generating: 'Generating your report...',

    // ResultDisplay.tsx (and its subcomponents)
    scanAgainButton: 'Scan Another Product',
    scannedImagesTitle: 'Scanned Images',
    analysisSummary: 'Key Findings',
    grade: 'Safety Grade',
    score: 'Score',
    safetyTips: 'Safety & Mitigation Tips',
    notes: 'Analyst Notes',
    ingredientDeepDive: 'Ingredient Deep Dive',
    riskLevel: 'Risk Level',
    hazards: 'Hazards',
    concentration: 'Concentration',
    incidentHistory: 'Incident History',
    noIncidents: 'No relevant incidents found.',
    incidentType: 'Type',
    date: 'Date',
    saferAlternatives: 'Safer Alternatives',
    noAlternatives: 'No specific alternatives recommended.',
    reason: 'Reason',
    environmentalImpact: 'Environmental Impact',
    ecoGrade: 'Eco-Grade',
    ecoScore: 'Eco-Score',
    packaging: 'Packaging Recyclability',
    keyFactors: 'Key Factors',
    disposalTip: 'Safe Disposal Tip',
    vulnerableGroupAnalysis: 'Vulnerable Group Analysis',
    vulnerableGroupPrompt: 'Refine analysis for specific sensitivities:',
    refining: 'Refining...',
    refinedAnalysisTitle: 'Detailed Analysis for {group}',
    baseAnalysisTitle: 'Base Analysis',
    productName: 'Product Name',
    category: 'Category',
    byBrand: 'by {brand}',
    noDataAvailable: 'No data available.',
    reportDate: 'Report Date',
    gradeSubtitles: {
        'Safe': 'Low risk detected for general use.',
        'Caution': 'Some ingredients may pose moderate risks. Use with care.',
        'High Risk': 'Contains ingredients with significant health & safety concerns.',
        'Eco-Friendly': 'Low environmental impact.',
        'Moderate Impact': 'Some environmental concerns identified.',
        'High Impact': 'Significant environmental impact.'
    },


    // Actions
    copyReport: 'Copy Text',
    reportCopied: 'Copied!',
    shareReport: 'Share',
    saveAsJpg: 'Save as JPG',
    saveAsTxt: 'Save as TXT',
    saving: 'Saving...',
    saved: 'Saved!',
    reportTitle: 'Anshim Scanner Analysis Report',


    // vulnerable modes from services/geminiService.ts
    vulnerableModes: {
        Infant: 'Infants',
        Pregnant: 'Pregnant Individuals',
        Pet: 'Pets',
        Respiratory: 'Individuals with Respiratory Sensitivities',
    },
  },
  ko: {
    // App.tsx
    headerTitle: '안심 스캐너',
    toggleToKorean: '한국어로 보기',
    toggleToEnglish: 'View in English',
    analysisFailedTitle: '분석 실패',
    tryAgainButton: '다시 시도',
    footerText: '© {year} 안심 스캐너. All rights reserved.',
    userManualLink: '사용자 매뉴얼',
    legalDisclaimerLink: '법적 고지',

    // DisclaimerModal.tsx
    disclaimerTitle: '법적 고지',
    disclaimerContent1: '정보 제공 목적: \'안심 스캐너\'가 제공하는 모든 분석 결과는 Google Gemini AI를 통해 생성된 정보이며, 참고용으로만 제공됩니다.',
    disclaimerContent2: '전문가 조언 대체 불가: 본 앱의 정보는 의학적, 법률적 또는 기타 전문적인 조언을 대체할 수 없습니다. 제품 사용과 관련된 건강상의 우려가 있는 경우, 반드시 의사나 전문가와 상담하시기 바랍니다.',
    disclaimerContent3: '책임의 한계: AI 분석에는 오류나 부정확성이 포함될 수 있습니다. 사용자는 제공된 정보를 바탕으로 내린 모든 결정에 대해 스스로 책임을 져야 하며, 개발팀은 이로 인해 발생하는 어떠한 직간접적인 손해에 대해서도 책임을 지지 않습니다.',
    iUnderstandButton: '확인 및 동의',

    // UserManualModal.tsx
    userManualTitle: '사용자 매뉴얼',
    closeButton: '닫기',
    userManualSections: [
      {
        title: '1. 시작하기',
        content: "앱을 처음 실행하면 제품 라벨을 스캔할 수 있는 초기 화면이 나타납니다. 우측 상단에서 언어(한국어/영어)를 선택할 수 있습니다."
      },
      {
        title: '2. 제품 라벨 스캔 및 분석',
        content: "1. 이미지 준비: 분석할 제품의 성분 목록이 잘 보이도록 선명하고 밝은 사진을 준비합니다. 성분 목록이 길 경우, 여러 장을 촬영해도 좋습니다.\n2. 이미지 업로드: '이미지 업로드' 버튼으로 저장된 사진을 선택하거나, '사진 찍기' 버튼으로 직접 촬영합니다.\n3. 미리보기 확인: 업로드한 이미지를 확인하고, 잘못된 이미지는 'X' 버튼을 눌러 삭제합니다.\n4. 분석 시작: 하단의 'N개 이미지 분석' 버튼을 클릭하여 AI 분석을 시작합니다."
      },
      {
        title: '3. 분석 결과 확인하기',
        content: "- 주요 분석 결과: 제품의 '안전 등급'과 '환경 등급'을 점수와 요약 설명으로 한눈에 파악합니다.\n- 취약 계층 분석: '영유아', '임산부' 등 특정 그룹 버튼을 클릭하여 해당 그룹에 맞춤화된 분석 결과를 확인합니다.\n- 상세 정보: '안전 사용 가이드', '성분 심층 분석', '환경 영향' 등 카드별 상세 내용을 확인합니다."
      },
      {
        title: '4. 결과 활용 및 새로 시작하기',
        content: "- 결과 저장/공유: 화면 하단 메뉴에서 '텍스트 복사', 'JPG로 저장', 'TXT로 저장' 기능을 사용할 수 있습니다.\n- 새로 시작하기: '다른 제품 스캔하기' 버튼을 눌러 초기 화면으로 돌아갑니다."
      }
    ],

    // Scanner.tsx
    scanTitle: '제품 라벨 스캔하기',
    scanModeOcr: '카메라로 스캔 (OCR)',
    multiOcrInfo: '정확한 분석을 위해, 밝은 곳에서 촬영한 선명한 성분표 이미지를 업로드해주세요. 성분 목록이 길 경우 여러 장을 촬영해 추가할 수 있습니다.',
    imagePreviewAlt: '이미지 미리보기 {index}',
    ocrButton: '이미지 업로드',
    addPhotoButton: '사진 찍기',
    analyzeButton: '{count}개 이미지 분석',

    // Spinner.tsx
    loadingText: '분석 준비 중...',
    loadingText_contacting: 'Gemini에 연결 중...',
    loadingText_analyzing: '제품 데이터 분석 중...',
    loadingText_generating: '보고서 생성 중...',

    // ResultDisplay.tsx (and its subcomponents)
    scanAgainButton: '다른 제품 스캔하기',
    scannedImagesTitle: '스캔된 이미지',
    analysisSummary: '주요 분석 결과',
    grade: '안전 등급',
    score: '점수',
    safetyTips: '안전 사용 가이드',
    notes: '분석가 노트',
    ingredientDeepDive: '성분 심층 분석',
    riskLevel: '위험도',
    hazards: '유해성',
    concentration: '농도',
    incidentHistory: '과거 사고 이력',
    noIncidents: '관련된 사고 이력을 찾을 수 없습니다.',
    incidentType: '유형',
    date: '날짜',
    saferAlternatives: '더 안전한 대안 제품',
    noAlternatives: '추천된 특정 대안 제품이 없습니다.',
    reason: '이유',
    environmentalImpact: '환경 영향',
    ecoGrade: '환경 등급',
    ecoScore: '환경 점수',
    packaging: '포장재 재활용성',
    keyFactors: '주요 요인',
    disposalTip: '안전한 폐기 팁',
    vulnerableGroupAnalysis: '취약 계층을 위한 분석 세분화',
    vulnerableGroupPrompt: '특정 민감도에 대한 분석 세분화:',
    refining: '분석 중...',
    refinedAnalysisTitle: '{group}에 대한 상세 분석',
    baseAnalysisTitle: '일반 분석',
    productName: '제품명',
    category: '제품 유형',
    byBrand: '브랜드: {brand}',
    noDataAvailable: '데이터 없음.',
    reportDate: '분석 일자',
    gradeSubtitles: {
        'Safe': '일반 사용에 대해 낮은 위험이 감지되었습니다.',
        'Caution': '일부 성분에 중간 수준의 위험이 있을 수 있습니다. 주의하여 사용하세요.',
        'High Risk': '건강 및 안전에 대한 심각한 우려가 있는 성분을 포함합니다.',
        'Eco-Friendly': '환경 영향이 적습니다.',
        'Moderate Impact': '일부 환경적 우려가 확인되었습니다.',
        'High Impact': '환경에 미치는 영향이 상당합니다.'
    },
    
    // Actions
    copyReport: '텍스트 복사',
    reportCopied: '복사됨!',
    shareReport: '공유하기',
    saveAsJpg: 'JPG로 저장',
    saveAsTxt: 'TXT로 저장',
    saving: '저장 중...',
    saved: '저장됨!',
    reportTitle: '안심 스캐너 분석 보고서',

    // vulnerable modes from services/geminiService.ts
    vulnerableModes: {
        Infant: '영유아',
        Pregnant: '임산부',
        Pet: '반려동물',
        Respiratory: '호흡기 민감군',
    },
  }
};